@xsuaaHostname = https://nus-ariba-dev-px55m7l5.authentication.eu10.hana.ondemand.com
@xsuaaClient = sb-utility!t169063
@xsuaaSecret = 8f6e922d-4d5d-4fe6-910f-000dce2b4638$tk1PCoekKMDcX4OIh88nJSgmdU2bERyXw_RLMtfY_vA=
@host = localhost:4004
@protocol = https
@unsecureProtocol = http
@userId = OT_CA9

### Request-1 Get xsuaa token
#==================================================================#
# @name getXsuaaToken

POST {{xsuaaHostname}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{xsuaaClient}}:{{xsuaaSecret}}

client_id={{xsuaaClient}}
&client_secret={{xsuaaSecret}}
&grant_type=client_credentials

### Store access token 
@access_token = {{getXsuaaToken.response.body.$.access_token}}

### Request-1 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/dummy()
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/util/getUserDetails(userId='PTT_CA9')
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-1 Get eclaims overview dashboard config
#==================================================================#
POST {{unsecureProtocol}}://{{host}}/eclaims/eclaimsOverviewDashboard
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

{
	"data": {
		"STF_NUMBER": "81535",
		"SF_STF_NUMBER": "81535",
		"PROCESS_CODE": "100"
	}
}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/approvermatrix/staff_based_usergroup_ulu_fdlu(staffId='81535',userGroup='CW_DEPARTMENT_ADMIN')
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/$metadata
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/fetchClaimTypes(staffId='21830',userGroup='CA_MONTH')
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/fetchUluFdlu(userGroup='CLAIM_ASSISTANT',claimType='103',period='undefined')
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/fetchUluFdlu?claimType=101&userGroup=CLAIM_ASSISTANT&period=05-2025
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
POST {{unsecureProtocol}}://{{host}}/eclaims/rateTypes
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

{"data":{"PROCESS_CODE":"101","CLAIM_MONTH":"08-2025","STAFF_ID":"151397","ULU":"0231054600","FDLU":"0005690002"}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/v2/eclaims/caStaffLookup?ulu=0301060200&fdlu=0006020001&claimType=101&period=05-2025
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/draftEclaimData(ulu='0231054600',fdlu='0005690002',claimType='103',period='04-2025',staffId='151398')
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/draftEclaimData?ulu=0210010100&fdlu=0001010001&claimType=102&period=04-2025&staffId=151515
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/claimantStaffInfo?username=151398
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/v2/eclaims/fetchWBS?staffId=151390&claimDate=2025-04-01
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/eclaimRequestViews('DT2504000002')?$top=10&$expand=MasterClaimTypeDetails,RemarksDataDetails,TaskActionConfigViewDetails,RequestLockDetailsDetails,AttachmentsDataDetails
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/eclaimAddtionalApproverViews
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/fetchCompInfoFromCPI?stfNumber=151398
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
POST {{unsecureProtocol}}://{{host}}/eclaims/validateEclaims
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

{
	"data": [
		{
			"CLAIM_TYPE": "101",
			"STAFF_ID": "151397",
			"CLAIM_REQUEST_TYPE": "Daily",
			"CLAIM_MONTH": "08-2025",
			"TOTAL_AMOUNT": " ",
			"WBS": " ",
			"ULU": "0231054600",
			"FDLU": "0005690002",
			"DRAFT_ID": "DT2509000009",
			"VERIFIER": [
				{
					"PPNT_ID": "PPNT25090003",
					"STAFF_ID": "22818",
					"NUSNET_ID": "PTT_VF9",
					"ULU": "",
					"FDLU": "",
					"STAFF_FULL_NAME": "Randal Krueger"
				}
			],
			"ADDTIONAL_APPROVER_1": [
				{
					"PPNT_ID": "PPNT25090001",
					"STAFF_ID": "30316",
					"NUSNET_ID": "PTT_AAP9_1",
					"ULU": "",
					"FDLU": "",
					"STAFF_FULL_NAME": "Carter Tavian"
				}
			],
			"ADDTIONAL_APPROVER_2": [
				{
					"PPNT_ID": "PPNT25090002",
					"STAFF_ID": "12330",
					"NUSNET_ID": "PTT_AAP9_2",
					"ULU": "",
					"FDLU": "",
					"STAFF_FULL_NAME": "Sofia Macias"
				}
			],
			"ATTACHMENTS": [],
			"REMARKS": [
				{
					"ID": "RMK250900001",
					"REFERENCE_ID": "DT2509000009",
					"REMARKS": "Hello I am a Claim Assistant",
					"STAFF_ID": "1625",
					"STAFF_NAME": "Aliviah Hasset",
					"STAFF_USER_TYPE": "CA",
					"REMARKS_UPDATE_ON": "2025-09-15 17:29:54",
					"REMARKS_TYPE": null,
					"NUSNET_ID": null,
					"IS_EDITABLE": 0,
					"__metadata": {
						"type": "EclaimsService.PRJ_REMARKS_DETAILS",
						"uri": "https://port8080-workspaces-ws-8qmdt.eu10.applicationstudio.cloud.sap,nusbtpeclaim.dest:443/destinations/nusbtpeclaim/odata/v2/eclaims/PRJ_REMARKS_DETAILS('RMK250900001')"
					}
				}
			],
			"REQUEST_STATUS": "01",
			"isMassUpload": "N",
			"isSave": "N",
			"ACTION": "SUBMIT",
			"ROLE": "CA",
			"REQUEST_ID": "",
			"selectedClaimDates": [
				{
					"ITEM_ID": "",
					"CLAIM_START_DATE": "2025-08-01",
					"CLAIM_END_DATE": "2025-08-01",
					"START_TIME": "11:00",
					"END_TIME": "16:00",
					"CLAIM_START_DATE_DISPLAY": "01 Aug, 2025",
					"CLAIM_DAY": "Friday",
					"HOURS_UNIT": "5.00",
					"RATE_TYPE": "10",
					"CLAIM_REQUEST_TYPE_NUMBER": "10",
					"CLAIM_DAY_TYPE": "Workday",
					"WBS": "",
					"WAGE_CODE": "",
					"REMARKS": "",
					"TOTAL_AMOUNT": "125.00",
					"IS_DISCREPENCY": 0,
					"RATE_TYPE_AMOUNT": "25.00",
					"DISC_RATETYPE_AMOUNT": "",
					"OT_COMMENCE_AFT_HRS": ""
				},
				{
					"ITEM_ID": "",
					"CLAIM_START_DATE": "2025-08-02",
					"CLAIM_END_DATE": "2025-08-02",
					"START_TIME": "11:00",
					"END_TIME": "16:00",
					"CLAIM_START_DATE_DISPLAY": "02 Aug, 2025",
					"CLAIM_DAY": "Saturday",
					"HOURS_UNIT": "5.00",
					"RATE_TYPE": "10",
					"CLAIM_REQUEST_TYPE_NUMBER": "10",
					"CLAIM_DAY_TYPE": "Workday",
					"WBS": "",
					"WAGE_CODE": "",
					"REMARKS": "",
					"TOTAL_AMOUNT": "150.00",
					"IS_DISCREPENCY": 0,
					"RATE_TYPE_AMOUNT": "30.00",
					"DISC_RATETYPE_AMOUNT": "",
					"OT_COMMENCE_AFT_HRS": ""
				},
				{
					"ITEM_ID": "",
					"CLAIM_START_DATE": "2025-08-03",
					"CLAIM_END_DATE": "2025-08-03",
					"START_TIME": "11:00",
					"END_TIME": "16:00",
					"CLAIM_START_DATE_DISPLAY": "03 Aug, 2025",
					"CLAIM_DAY": "Sunday",
					"HOURS_UNIT": "5.00",
					"RATE_TYPE": "10",
					"CLAIM_REQUEST_TYPE_NUMBER": "10",
					"CLAIM_DAY_TYPE": "Workday",
					"WBS": "",
					"WAGE_CODE": "",
					"REMARKS": "",
					"TOTAL_AMOUNT": "125.00",
					"IS_DISCREPENCY": 0,
					"RATE_TYPE_AMOUNT": "25.00",
					"DISC_RATETYPE_AMOUNT": "",
					"OT_COMMENCE_AFT_HRS": ""
				}
			]
		}
	]
}

### Request-2 Get eclaims header data
#==================================================================#
POST {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/rest/ecpWbsValidate
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

{
	"data" : {"WBSRequest":{"WBS":["A-0000009-00-00","A-0000019-04-00","A-0000021-01-00"]}}
}

### Request-2 Get eclaims header data
#==================================================================#
POST {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/singleRequest
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

{
	"data" : [
        {
          "CLAIM_TYPE": "101",
          "STAFF_ID": "151407",
          "CLAIM_REQUEST_TYPE": "Daily",
          "CLAIM_MONTH": "06-2025",
          "TOTAL_AMOUNT": " ",
          "WBS": " ",
          "ULU": "0301060200",
          "FDLU": "0006020001",
          "DRAFT_ID": "",
          "VERIFIER": [
            {
              "PPNT_ID": "",
              "STAFF_ID": "",
              "NUSNET_ID": "",
              "ULU": "",
              "FDLU": "",
              "STAFF_FULL_NAME": ""
            }
          ],
          "ADDTIONAL_APPROVER_1": [
            {
              "PPNT_ID": "",
              "STAFF_ID": "",
              "NUSNET_ID": "",
              "ULU": "",
              "FDLU": "",
              "STAFF_FULL_NAME": ""
            }
          ],
          "ADDTIONAL_APPROVER_2": [
            {
              "PPNT_ID": "",
              "STAFF_ID": "",
              "NUSNET_ID": "",
              "ULU": "",
              "FDLU": "",
              "STAFF_FULL_NAME": ""
            }
          ],
          "ATTACHMENTS": [],
          "REQUEST_STATUS": "01",
          "isMassUpload": "N",
          "isSave": "Y",
          "ACTION": "SAVE",
          "ROLE": "CA",
          "REQUEST_ID": "",
          "selectedClaimDates": []
        }
    ]
}