@xsuaaHostname = https://nus-ariba-dev-px55m7l5.authentication.eu10.hana.ondemand.com
@xsuaaClient = sb-utility!t169063
@xsuaaSecret = 8f6e922d-4d5d-4fe6-910f-000dce2b4638$tk1PCoekKMDcX4OIh88nJSgmdU2bERyXw_RLMtfY_vA=
@host = localhost:4004
@protocol = https
@unsecureProtocol = http
@userId = PTT_CA9

### Request-1 Get xsuaa token
#==================================================================#
# @name getXsuaaToken

POST {{xsuaaHostname}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{xsuaaClient}}:{{xsuaaSecret}}

client_id={{xsuaaClient}}
&client_secret={{xsuaaSecret}}
&grant_type=client_credentials

### Store access token 
@access_token = {{getXsuaaToken.response.body.$.access_token}}

### Request-1 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/dummy()
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/util/getUserDetails(userId='PTT_CA9')
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-1 Get eclaims overview dashboard config
#==================================================================#
POST {{unsecureProtocol}}://{{host}}/eclaims/eclaimsOverviewDashboard
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

{
	"data": {
		"STF_NUMBER": "81535",
		"SF_STF_NUMBER": "81535",
		"PROCESS_CODE": "100"
	}
}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/approvermatrix/staff_based_usergroup_ulu_fdlu(staffId='81535',userGroup='CW_DEPARTMENT_ADMIN')
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/$metadata
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/fetchClaimTypes(staffId='21830',userGroup='CA_MONTH')
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/fetchUluFdlu(userGroup='CLAIM_ASSISTANT',claimType='103',period='undefined')
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/fetchUluFdlu?claimType=101&userGroup=CLAIM_ASSISTANT&period=05-2025
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
POST {{unsecureProtocol}}://{{host}}/eclaims/rateTypes
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

{"data":{"PROCESS_CODE":"101","CLAIM_MONTH":"08-2025","STAFF_ID":"151397","ULU":"0231054600","FDLU":"0005690002"}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/v2/eclaims/caStaffLookup?ulu=0301060200&fdlu=0006020001&claimType=101&period=05-2025
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/draftEclaimData(ulu='0231054600',fdlu='0005690002',claimType='103',period='04-2025',staffId='151398')
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/draftEclaimData?ulu=0210010100&fdlu=0001010001&claimType=102&period=04-2025&staffId=151515
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/claimantStaffInfo?username=151398
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/v2/eclaims/fetchWBS?staffId=151390&claimDate=2025-04-01
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/eclaimRequestViews('DT2504000002')?$top=10&$expand=MasterClaimTypeDetails,RemarksDataDetails,TaskActionConfigViewDetails,RequestLockDetailsDetails,AttachmentsDataDetails
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/eclaimAddtionalApproverViews
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/fetchCompInfoFromCPI?stfNumber=151398
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

### Request-2 Get eclaims header data
#==================================================================#
POST {{unsecureProtocol}}://{{host}}/eclaims/validateEclaims
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

{
  "data": [
    {
      "CLAIM_TYPE": "104",
      "STAFF_ID": "151415",
      "CLAIM_REQUEST_TYPE": "Daily",
      "CLAIM_MONTH": "02-2025",
      "TOTAL_AMOUNT": " ",
      "WBS": " ",
      "ULU": "0210010100",
      "FDLU": "0001270002",
      "DRAFT_ID": "DT2504000002",
      "VERIFIER": [
        {
          "PPNT_ID": "",
          "STAFF_ID": "",
          "NUSNET_ID": "",
          "ULU": "",
          "FDLU": "",
          "STAFF_FULL_NAME": ""
        }
      ],
      "ADDTIONAL_APPROVER_1": [
        {
          "PPNT_ID": "",
          "STAFF_ID": "",
          "NUSNET_ID": "",
          "ULU": "",
          "FDLU": "",
          "STAFF_FULL_NAME": ""
        }
      ],
      "ADDTIONAL_APPROVER_2": [
        {
          "PPNT_ID": "",
          "STAFF_ID": "",
          "NUSNET_ID": "",
          "ULU": "",
          "FDLU": "",
          "STAFF_FULL_NAME": ""
        }
      ],
      "ATTACHMENTS": [],
      "REMARKS": [],
      "REQUEST_STATUS": "01",
      "isMassUpload": "N",
      "isSave": "N",
      "ACTION": "SUBMIT",
      "ROLE": "CA",
      "REQUEST_ID": "",
      "selectedClaimDates": [
        {
          "ITEM_ID": "",
          "CLAIM_START_DATE": "2025-02-01",
          "CLAIM_END_DATE": "2025-02-01",
          "START_TIME": "11:00",
          "END_TIME": "12:00",
          "CLAIM_START_DATE_DISPLAY": "01 Feb, 2025",
          "CLAIM_DAY": "Saturday",
          "HOURS_UNIT": "1.00",
          "RATE_TYPE": "",
          "CLAIM_REQUEST_TYPE_NUMBER": "",
          "CLAIM_DAY_TYPE": "Offday",
          "WBS": "A-0000009-00-00",
          "WAGE_CODE": "",
          "REMARKS": "",
          "TOTAL_AMOUNT": "",
          "IS_DISCREPENCY": 0,
          "RATE_TYPE_AMOUNT": "",
          "DISC_RATETYPE_AMOUNT": "",
          "IS_PH": 3,
          "OT_COMMENCE_AFT_HRS": ""
        },
        {
          "ITEM_ID": "",
          "CLAIM_START_DATE": "2025-02-02",
          "CLAIM_END_DATE": "2025-02-02",
          "START_TIME": "11:00",
          "END_TIME": "12:00",
          "CLAIM_START_DATE_DISPLAY": "02 Feb, 2025",
          "CLAIM_DAY": "Sunday",
          "HOURS_UNIT": "1.00",
          "RATE_TYPE": "",
          "CLAIM_REQUEST_TYPE_NUMBER": "",
          "CLAIM_DAY_TYPE": "Restday",
          "WBS": "A-0000009-00-00",
          "WAGE_CODE": "",
          "REMARKS": "",
          "TOTAL_AMOUNT": "",
          "IS_DISCREPENCY": 0,
          "RATE_TYPE_AMOUNT": "",
          "DISC_RATETYPE_AMOUNT": "",
          "IS_PH": 1,
          "OT_COMMENCE_AFT_HRS": ""
        }
      ]
    }
  ]
}

### Request-2 Get eclaims header data
#==================================================================#
POST {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/rest/ecpWbsValidate
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

{
	"data" : {"WBSRequest":{"WBS":["A-0000009-00-00","A-0000019-04-00","A-0000021-01-00"]}}
}

### Request-2 Get eclaims header data
#==================================================================#
POST {{unsecureProtocol}}://{{host}}/odata/v2/eclaims/singleRequest
Content-Type: application/json
Authorization: Bearer {{access_token}}
X-User-Id: {{userId}}

{
	"data" : [
        {
          "CLAIM_TYPE": "101",
          "STAFF_ID": "151407",
          "CLAIM_REQUEST_TYPE": "Daily",
          "CLAIM_MONTH": "06-2025",
          "TOTAL_AMOUNT": " ",
          "WBS": " ",
          "ULU": "0301060200",
          "FDLU": "0006020001",
          "DRAFT_ID": "",
          "VERIFIER": [
            {
              "PPNT_ID": "",
              "STAFF_ID": "",
              "NUSNET_ID": "",
              "ULU": "",
              "FDLU": "",
              "STAFF_FULL_NAME": ""
            }
          ],
          "ADDTIONAL_APPROVER_1": [
            {
              "PPNT_ID": "",
              "STAFF_ID": "",
              "NUSNET_ID": "",
              "ULU": "",
              "FDLU": "",
              "STAFF_FULL_NAME": ""
            }
          ],
          "ADDTIONAL_APPROVER_2": [
            {
              "PPNT_ID": "",
              "STAFF_ID": "",
              "NUSNET_ID": "",
              "ULU": "",
              "FDLU": "",
              "STAFF_FULL_NAME": ""
            }
          ],
          "ATTACHMENTS": [],
          "REQUEST_STATUS": "01",
          "isMassUpload": "N",
          "isSave": "Y",
          "ACTION": "SAVE",
          "ROLE": "CA",
          "REQUEST_ID": "",
          "selectedClaimDates": []
        }
    ]
}