@xsuaaHostname = https://nus-ariba-dev-px55m7l5.authentication.eu10.hana.ondemand.com
@xsuaaClient = sb-utility!t169063
@xsuaaSecret = 8f6e922d-4d5d-4fe6-910f-000dce2b4638$tk1PCoekKMDcX4OIh88nJSgmdU2bERyXw_RLMtfY_vA=
@host = localhost:4004
@protocol = https
@unsecureProtocol = http

### Request-1 Get xsuaa token
#==================================================================#
# @name getXsuaaToken

POST {{xsuaaHostname}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{xsuaaClient}}:{{xsuaaSecret}}

client_id={{xsuaaClient}}
&client_secret={{xsuaaSecret}}
&grant_type=client_credentials

### Store access token 
@access_token = {{getXsuaaToken.response.body.$.access_token}}

### Request-1 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/dummy()
Content-Type: application/json
Authorization: Bearer {{access_token}}


### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/util/getUserDetails(userId='PTT_CA9')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-1 Get eclaims overview dashboard config
#==================================================================#
POST {{unsecureProtocol}}://{{host}}/eclaims/eclaimsOverviewDashboard
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
	"data": {
		"STF_NUMBER": "81535",
		"SF_STF_NUMBER": "81535",
		"PROCESS_CODE": "100"
	}
}



### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/approvermatrix/staff_based_usergroup_ulu_fdlu(staffId='81535',userGroup='CW_DEPARTMENT_ADMIN')
Content-Type: application/json
Authorization: Bearer {{access_token}}


### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/v2/eclaims/$metadata
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/fetchClaimTypes(staffId='21830',userGroup='CA_MONTH')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/fetchUluFdlu(userGroup='CLAIM_ASSISTANT',claimType='103',period='undefined')
Content-Type: application/json
Authorization: Bearer {{access_token}}


### Request-2 Get eclaims header data
#==================================================================#
POST {{unsecureProtocol}}://{{host}}/eclaims/rateTypes
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
	"data" : {"PROCESS_CODE":"104","CLAIM_MONTH":"05-2025","STAFF_ID":"151401","ULU":"0231054600","FDLU":"0005690002"}
}


### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/caStaffLookup(ulu='0261046100',fdlu='0004630003',claimType='101',period='05-2025')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/draftEclaimData(ulu='0231054600',fdlu='0005690002',claimType='103',period='04-2025',staffId='151398')
Content-Type: application/json
Authorization: Bearer {{access_token}}


### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/v2/eclaims/draftEclaimData?ulu=0210010100&fdlu=0001010001&claimType=102&period=04-2025&staffId=151515
Content-Type: application/json
Authorization: Bearer {{access_token}}


### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/v2/eclaims/claimantStaffInfo?username=151398
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/catalog/$metadata
Content-Type: application/json
Authorization: Bearer {{access_token}}